# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Matterhorn Lab
tagline:          'Matterhorn Lab'
description:      'An advanced web app for investors searching information about Swiss market large-cap stocks.'
url:              https://matterhornlab.github.io
baseurl:          /

author:
  name:           'Sebastian A. Ott Nikola Racic Ognjen Divljak Benjamin Vomel Przemek Warnel'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           
